version: "3"

services:
#    webapp:
#        build: ./ng-photoLibrary
#        ports: 
#            - "8080:80"
#        volumes:
#            - /googleCredentials:/googleCredentials

    pyapp:
        build: ./py-photoLibrary
        ports:
            - "8080:5000"
