version: "3"

services:
    webapp:
        build: ./ng-photoLibrary
        ports:
            - "8080:80"
        volumes:
            - /googleCredentials:/googleCredentials

    app:
        build: ./pi-photoLibrary
        ports:
            - "5000:5000"
        volumes:
            - "/photos:/mnt/md0/share/photos"
            - "/CF:/CF"
            - "/googleCredentials:/googleCredentials"
